# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QHeaderView, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QTabWidget,
    QTableView, QWidget)

class Ui_MyApp(object):
    def setupUi(self, MyApp):
        if not MyApp.objectName():
            MyApp.setObjectName(u"MyApp")
        MyApp.resize(1920, 1000)
        MyApp.setAutoFillBackground(False)
        self.tabWidget = QTabWidget(MyApp)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 1181, 1000))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.tab_1.setEnabled(True)
        self.tab_1.setAutoFillBackground(True)
        self.tab_1.setStyleSheet(u"")
        self.selectFolderButton = QPushButton(self.tab_1)
        self.selectFolderButton.setObjectName(u"selectFolderButton")
        self.selectFolderButton.setGeometry(QRect(10, 80, 91, 23))
        self.folderEdit = QLineEdit(self.tab_1)
        self.folderEdit.setObjectName(u"folderEdit")
        self.folderEdit.setGeometry(QRect(110, 80, 371, 21))
        self.LoadDataButton = QPushButton(self.tab_1)
        self.LoadDataButton.setObjectName(u"LoadDataButton")
        self.LoadDataButton.setGeometry(QRect(10, 130, 471, 41))
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setEnabled(False)
        self.tab_2.setAutoFillBackground(True)
        self.tab_2.setStyleSheet(u"")
        self.PETHView_2 = QGraphicsView(self.tab_2)
        self.PETHView_2.setObjectName(u"PETHView_2")
        self.PETHView_2.setGeometry(QRect(790, 665, 281, 131))
        self.unit2Edit = QLineEdit(self.tab_2)
        self.unit2Edit.setObjectName(u"unit2Edit")
        self.unit2Edit.setGeometry(QRect(201, 90, 41, 20))
        self.unit2Edit.setReadOnly(True)
        self.selectUnitsButton = QPushButton(self.tab_2)
        self.selectUnitsButton.setObjectName(u"selectUnitsButton")
        self.selectUnitsButton.setGeometry(QRect(510, 470, 75, 23))
        self.undoButton = QPushButton(self.tab_2)
        self.undoButton.setObjectName(u"undoButton")
        self.undoButton.setGeometry(QRect(660, 113, 101, 31))
        self.Unit1_label = QLabel(self.tab_2)
        self.Unit1_label.setObjectName(u"Unit1_label")
        self.Unit1_label.setGeometry(QRect(250, 60, 241, 20))
        self.Unit1_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.splitButton = QPushButton(self.tab_2)
        self.splitButton.setObjectName(u"splitButton")
        self.splitButton.setGeometry(QRect(540, 113, 101, 31))
        self.Unit2_label = QLabel(self.tab_2)
        self.Unit2_label.setObjectName(u"Unit2_label")
        self.Unit2_label.setGeometry(QRect(250, 90, 241, 20))
        self.Unit2_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.unit1Edit = QLineEdit(self.tab_2)
        self.unit1Edit.setObjectName(u"unit1Edit")
        self.unit1Edit.setGeometry(QRect(201, 60, 41, 20))
        self.unit1Edit.setReadOnly(True)
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 130, 81, 20))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 70, 51, 31))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.saveButton = QPushButton(self.tab_2)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(790, 61, 271, 81))
        self.depthView = QGraphicsView(self.tab_2)
        self.depthView.setObjectName(u"depthView")
        self.depthView.setGeometry(QRect(420, 170, 341, 276))
        self.clusterEdit = QLineEdit(self.tab_2)
        self.clusterEdit.setObjectName(u"clusterEdit")
        self.clusterEdit.setGeometry(QRect(71, 70, 51, 31))
        self.allUnitsButton = QPushButton(self.tab_2)
        self.allUnitsButton.setObjectName(u"allUnitsButton")
        self.allUnitsButton.setGeometry(QRect(420, 470, 75, 23))
        self.PETHView_1 = QGraphicsView(self.tab_2)
        self.PETHView_1.setObjectName(u"PETHView_1")
        self.PETHView_1.setGeometry(QRect(790, 500, 281, 131))
        self.nextButton = QPushButton(self.tab_2)
        self.nextButton.setObjectName(u"nextButton")
        self.nextButton.setGeometry(QRect(660, 61, 101, 31))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(140, 60, 51, 20))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(140, 90, 51, 20))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.similarityMatrixView = QGraphicsView(self.tab_2)
        self.similarityMatrixView.setObjectName(u"similarityMatrixView")
        self.similarityMatrixView.setGeometry(QRect(70, 190, 256, 256))
        self.unitsToSplitEdit = QLineEdit(self.tab_2)
        self.unitsToSplitEdit.setObjectName(u"unitsToSplitEdit")
        self.unitsToSplitEdit.setGeometry(QRect(110, 130, 371, 20))
        self.unitsToSplitEdit.setReadOnly(False)
        self.unitsToSplitEdit.setClearButtonEnabled(True)
        self.waveformView = QGraphicsView(self.tab_2)
        self.waveformView.setObjectName(u"waveformView")
        self.waveformView.setGeometry(QRect(420, 500, 341, 461))
        self.PETHView_3 = QGraphicsView(self.tab_2)
        self.PETHView_3.setObjectName(u"PETHView_3")
        self.PETHView_3.setGeometry(QRect(790, 830, 281, 131))
        self.selectedUnitsView = QGraphicsView(self.tab_2)
        self.selectedUnitsView.setObjectName(u"selectedUnitsView")
        self.selectedUnitsView.setGeometry(QRect(70, 170, 256, 16))
        self.previousButton = QPushButton(self.tab_2)
        self.previousButton.setObjectName(u"previousButton")
        self.previousButton.setGeometry(QRect(540, 61, 101, 31))
        self.colorbarView = QGraphicsView(self.tab_2)
        self.colorbarView.setObjectName(u"colorbarView")
        self.colorbarView.setGeometry(QRect(340, 346, 20, 100))
        self.label_colorbar_min = QLabel(self.tab_2)
        self.label_colorbar_min.setObjectName(u"label_colorbar_min")
        self.label_colorbar_min.setGeometry(QRect(364, 435, 41, 20))
        self.label_colorbar_min.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_colorbar_max = QLabel(self.tab_2)
        self.label_colorbar_max.setObjectName(u"label_colorbar_max")
        self.label_colorbar_max.setGeometry(QRect(364, 337, 41, 20))
        self.label_colorbar_max.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(330, 313, 60, 30))
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setWordWrap(False)
        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(906, 483, 53, 15))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(906, 648, 53, 15))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(906, 813, 53, 15))
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.acgView = QGraphicsView(self.tab_2)
        self.acgView.setObjectName(u"acgView")
        self.acgView.setGeometry(QRect(790, 170, 276, 276))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tab_3.setEnabled(False)
        self.tab_3.setAutoFillBackground(True)
        self.tab_3.setStyleSheet(u"")
        self.label_11 = QLabel(self.tab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 60, 51, 20))
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.clusterMergeEdit_1 = QLineEdit(self.tab_3)
        self.clusterMergeEdit_1.setObjectName(u"clusterMergeEdit_1")
        self.clusterMergeEdit_1.setGeometry(QRect(71, 60, 51, 20))
        self.clusterMergeEdit_1.setReadOnly(False)
        self.clusterMergeEdit_2 = QLineEdit(self.tab_3)
        self.clusterMergeEdit_2.setObjectName(u"clusterMergeEdit_2")
        self.clusterMergeEdit_2.setGeometry(QRect(71, 90, 51, 20))
        self.clusterMergeEdit_2.setReadOnly(False)
        self.label_12 = QLabel(self.tab_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 90, 51, 20))
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mergeButton = QPushButton(self.tab_3)
        self.mergeButton.setObjectName(u"mergeButton")
        self.mergeButton.setGeometry(QRect(540, 113, 101, 31))
        self.tableView = QTableView(self.tab_3)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(70, 500, 256, 461))
        self.cluster1_size_label = QLabel(self.tab_3)
        self.cluster1_size_label.setObjectName(u"cluster1_size_label")
        self.cluster1_size_label.setGeometry(QRect(130, 60, 31, 20))
        self.cluster1_size_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.cluster2_size_label = QLabel(self.tab_3)
        self.cluster2_size_label.setObjectName(u"cluster2_size_label")
        self.cluster2_size_label.setGeometry(QRect(130, 90, 31, 20))
        self.cluster2_size_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.PETH_Fig1 = QGraphicsView(MyApp)
        self.PETH_Fig1.setObjectName(u"PETH_Fig1")
        self.PETH_Fig1.setGeometry(QRect(1190, 20, 720, 480))
        self.PETH_Fig2 = QGraphicsView(MyApp)
        self.PETH_Fig2.setObjectName(u"PETH_Fig2")
        self.PETH_Fig2.setGeometry(QRect(1190, 510, 720, 480))
        self.sessionNumEdit = QLineEdit(MyApp)
        self.sessionNumEdit.setObjectName(u"sessionNumEdit")
        self.sessionNumEdit.setGeometry(QRect(430, 40, 51, 20))
        self.sessionNumEdit.setReadOnly(True)
        self.label_8 = QLabel(MyApp)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(170, 40, 81, 20))
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.unitNumEdit = QLineEdit(MyApp)
        self.unitNumEdit.setObjectName(u"unitNumEdit")
        self.unitNumEdit.setGeometry(QRect(260, 40, 51, 20))
        self.unitNumEdit.setReadOnly(True)
        self.label_10 = QLabel(MyApp)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(320, 40, 101, 20))
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.animalEdit = QLineEdit(MyApp)
        self.animalEdit.setObjectName(u"animalEdit")
        self.animalEdit.setGeometry(QRect(70, 40, 81, 20))
        self.animalEdit.setReadOnly(True)
        self.label_9 = QLabel(MyApp)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(9, 40, 51, 20))
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.clusterNumEdit = QLineEdit(MyApp)
        self.clusterNumEdit.setObjectName(u"clusterNumEdit")
        self.clusterNumEdit.setGeometry(QRect(600, 40, 51, 20))
        self.clusterNumEdit.setReadOnly(True)
        self.label_14 = QLabel(MyApp)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(490, 40, 101, 20))
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(MyApp)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MyApp)
    # setupUi

    def retranslateUi(self, MyApp):
        MyApp.setWindowTitle(QCoreApplication.translate("MyApp", u"MyApp", None))
#if QT_CONFIG(tooltip)
        self.tab_1.setToolTip(QCoreApplication.translate("MyApp", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.tab_1.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.selectFolderButton.setText(QCoreApplication.translate("MyApp", u"Select folder", None))
        self.folderEdit.setText("")
        self.LoadDataButton.setText(QCoreApplication.translate("MyApp", u"Load data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MyApp", u"Load data", None))
        self.selectUnitsButton.setText(QCoreApplication.translate("MyApp", u"Separated", None))
        self.undoButton.setText(QCoreApplication.translate("MyApp", u"Undo", None))
        self.Unit1_label.setText(QCoreApplication.translate("MyApp", u"Anm_Session_Unit", None))
        self.splitButton.setText(QCoreApplication.translate("MyApp", u"Split", None))
        self.Unit2_label.setText(QCoreApplication.translate("MyApp", u"Anm_Session_Unit", None))
        self.label_7.setText(QCoreApplication.translate("MyApp", u"Units to split:", None))
        self.label_4.setText(QCoreApplication.translate("MyApp", u"Cluster:", None))
        self.saveButton.setText(QCoreApplication.translate("MyApp", u"Save", None))
        self.allUnitsButton.setText(QCoreApplication.translate("MyApp", u"All", None))
        self.nextButton.setText(QCoreApplication.translate("MyApp", u"Next cluster", None))
        self.label_5.setText(QCoreApplication.translate("MyApp", u"Unit1:", None))
        self.label_6.setText(QCoreApplication.translate("MyApp", u"Unit2:", None))
        self.unitsToSplitEdit.setText("")
        self.previousButton.setText(QCoreApplication.translate("MyApp", u"Previous cluster", None))
        self.label_colorbar_min.setText(QCoreApplication.translate("MyApp", u"0.5", None))
        self.label_colorbar_max.setText(QCoreApplication.translate("MyApp", u"3.5", None))
        self.label_13.setText(QCoreApplication.translate("MyApp", u"Similarity", None))
        self.label.setText(QCoreApplication.translate("MyApp", u"Press", None))
        self.label_2.setText(QCoreApplication.translate("MyApp", u"Release", None))
        self.label_3.setText(QCoreApplication.translate("MyApp", u"Reward", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MyApp", u"Splitting", None))
        self.label_11.setText(QCoreApplication.translate("MyApp", u"Cluster1:", None))
        self.label_12.setText(QCoreApplication.translate("MyApp", u"Cluster2:", None))
        self.mergeButton.setText(QCoreApplication.translate("MyApp", u"Merge", None))
        self.cluster1_size_label.setText(QCoreApplication.translate("MyApp", u"(00)", None))
        self.cluster2_size_label.setText(QCoreApplication.translate("MyApp", u"(00)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MyApp", u"Merging", None))
        self.label_8.setText(QCoreApplication.translate("MyApp", u"Unit number:", None))
        self.label_10.setText(QCoreApplication.translate("MyApp", u"Session number:", None))
        self.label_9.setText(QCoreApplication.translate("MyApp", u"Animal:", None))
        self.label_14.setText(QCoreApplication.translate("MyApp", u"Cluster number:", None))
    # retranslateUi

